services:
    db:
        image: postgres:17
        container_name: agriflow_postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
            POSTGRES_DB: mydb
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    backend:
        build: ./backend
        env_file:
            - ./backend/.env.docker
        depends_on:
            - db
        ports:
            - "8000:8000"

volumes:
    postgres_data:
