"""
AgriFlow Model Registry
========================

Central import hub for all SQLAlchemy ORM models. Every model must be imported
here so that Alembic's autogenerate can discover table definitions when creating
database migrations.

Domain Model Overview:
    - User / Role: Authentication and role-based access control.
    - Plantation / PlantationLease: Crop source locations and their lease agreements.
    - BatchStage / Batch: Physical material quantities tracked through processing
      stages (HARVEST -> CLEAN -> DRY -> BAG -> GRADE -> PACK -> RETAIL) with
      parent-child lineage via self-referencing FK.
    - TransformationType / Transformation / TransformationInput / TransformationOutput:
      Processing events that consume input batches and produce output batches.
    - WageType / Personnel / TransformationPersonnel: Worker management with
      historical cost freezing on transformation assignments.
    - Vehicle / TransformationVehicle: Vehicle tracking with frozen cost-per-hour
      at time of usage.
    - Consumable / ConsumablePurchase / ConsumableConsumption / ConsumptionAllocation:
      Consumable inventory with FIFO (First-In-First-Out) costing via purchase lot
      allocation.
    - Customer: Customer records for tracking sale recipients.
    - Sale / SaleAllocation: Retail sales allocated directly against batches with
      FIFO or manual cost-of-goods-sold allocation.
    - ExpenseCategory / Expense: General overhead expenses optionally linked to
      plantations or vehicles.
    - Location: Geographic coordinates tied to plantations.
    - Weather: Historical weather data linked to locations.
    - AppConfig: Key/value store for runtime-configurable application settings.
"""

from ..database import Base
from .batch import Batch, BatchParent, BatchStage
from .consumables import (
    Consumable,
    ConsumableCategory,
    ConsumableConsumption,
    ConsumablePurchase,
    ConsumptionAllocation,
)
from .expense import Expense, ExpenseCategory
from .location import Location
from .personnel import Personnel, TransformationPersonnel, WageType
from .plantation import Plantation, PlantationLease
from .customer import Customer
from .sales import Sale, SaleAllocation
from .transformation import (
    Transformation,
    TransformationInput,
    TransformationOutput,
    TransformationType,
)
from .user import Role, User
from .vehicle import TransformationVehicle, Vehicle
from .settings import AppConfig
from .weather import Weather
from .approval import ApprovalRequest

# Import all models here so Alembic can discover them.
# Alembic's env.py imports Base.metadata; every model class that inherits from
# Base must be imported before that happens, otherwise its table will not appear
# in autogenerated migrations.
__all__ = [
    "Base",
    "User",
    "Role",
    "Plantation",
    "PlantationLease",
    "Vehicle",
    "Personnel",
    "WageType",
    "ConsumableCategory",
    "Consumable",
    "Batch",
    "BatchParent",
    "BatchStage",
    "TransformationType",
    "Transformation",
    "TransformationInput",
    "TransformationOutput",
    "TransformationPersonnel",
    "ConsumablePurchase",
    "ConsumableConsumption",
    "ConsumptionAllocation",
    "TransformationVehicle",
    "Customer",
    "Sale",
    "SaleAllocation",
    "Expense",
    "ExpenseCategory",
    "Location",
    "Weather",
    "AppConfig",
    "ApprovalRequest",
]
