FROM python:3.12-slim

WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

# Copy dependency files first (for Docker layer caching)
COPY pyproject.toml uv.lock ./
# Install dependencies into project virtual environment
RUN uv sync --frozen --no-dev

# Copy rest of the application
COPY . .

EXPOSE 8000

# CMD ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
CMD uv run uvicorn app.main:app --host 0.0.0.0 --port $PORT
