"""Created Consumables Category for better filtering

Revision ID: 2b61689ecbac
Revises: a1c3f7e82d50
Create Date: 2026-03-10 10:36:05.621413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b61689ecbac'
down_revision: Union[str, Sequence[str], None] = 'a1c3f7e82d50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumable_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumable_categories_name'), 'consumable_categories', ['name'], unique=True)
    op.add_column('consumables', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'consumables', 'consumable_categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'consumables', type_='foreignkey')
    op.drop_column('consumables', 'category_id')
    op.drop_index(op.f('ix_consumable_categories_name'), table_name='consumable_categories')
    op.drop_table('consumable_categories')
    # ### end Alembic commands ###
