"""Add batch level for sorting

Revision ID: 40c37e66c12a
Revises: 8bc7955f0bdb
Create Date: 2026-03-16 17:06:43.159634

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "40c37e66c12a"
down_revision: Union[str, Sequence[str], None] = "8bc7955f0bdb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "batch_stages", sa.Column("batch_stage_level", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("batch_stages", "batch_stage_level")
    # ### end Alembic commands ###
