"""plantation_weather_appconfig_refactor

Revision ID: 4393b725e9d5
Revises: 956695790b8c
Create Date: 2026-03-09 15:08:59.929328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4393b725e9d5'
down_revision: Union[str, Sequence[str], None] = '956695790b8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.alter_column('plantation_leases', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('plantations', sa.Column('area_hectares', sa.Numeric(precision=12, scale=4), nullable=True))
    op.alter_column('plantations', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('plantations', 'area')
    op.add_column('weather', sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('weather', sa.Column('is_manual', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('weather', sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    op.create_index(op.f('ix_weather_fetched_at'), 'weather', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_weather_location_id'), 'weather', ['location_id'], unique=False)
    op.drop_column('weather', 'created_at')
    op.drop_column('weather', 'temperature_c')
    op.drop_column('weather', 'humidity_percent')
    op.drop_column('weather', 'precipitation_mm')
    op.drop_column('weather', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('weather', sa.Column('precipitation_mm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('weather', sa.Column('humidity_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('weather', sa.Column('temperature_c', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('weather', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_weather_location_id'), table_name='weather')
    op.drop_index(op.f('ix_weather_fetched_at'), table_name='weather')
    op.drop_column('weather', 'raw_json')
    op.drop_column('weather', 'is_manual')
    op.drop_column('weather', 'fetched_at')
    op.add_column('plantations', sa.Column('area', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.alter_column('plantations', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('plantations', 'area_hectares')
    op.alter_column('plantation_leases', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_table('app_config')
    # ### end Alembic commands ###
