"""fix relationsip in personnel model

Revision ID: 464e5db19de0
Revises: 4fcd4dc5f46d
Create Date: 2026-02-18 13:09:49.472524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '464e5db19de0'
down_revision: Union[str, Sequence[str], None] = '4fcd4dc5f46d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transformation_personnel', sa.Column('wage_type_at_time_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('transformation_personnel_wage_type_at_time_fkey'), 'transformation_personnel', type_='foreignkey')
    op.create_foreign_key(None, 'transformation_personnel', 'wage_types', ['wage_type_at_time_id'], ['id'])
    op.drop_column('transformation_personnel', 'wage_type_at_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transformation_personnel', sa.Column('wage_type_at_time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transformation_personnel', type_='foreignkey')
    op.create_foreign_key(op.f('transformation_personnel_wage_type_at_time_fkey'), 'transformation_personnel', 'wage_types', ['wage_type_at_time'], ['id'])
    op.drop_column('transformation_personnel', 'wage_type_at_time_id')
    # ### end Alembic commands ###
