"""Updated Models with proper measures to retain data historically

Revision ID: 5965b2d7ae05
Revises: 55d1035ec8c0
Create Date: 2026-02-18 07:45:14.187695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5965b2d7ae05'
down_revision: Union[str, Sequence[str], None] = '55d1035ec8c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consumables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumables_name'), 'consumables', ['name'], unique=True)
    op.create_table('plantations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=False),
    sa.Column('lease_start', sa.DateTime(), nullable=False),
    sa.Column('lease_end', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.DateTime(), nullable=False),
    sa.Column('quantity_sold', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_of_goods_sold', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('customer_address', sa.String(length=500), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sale_date', 'sales', ['sale_date'], unique=False)
    op.create_index(op.f('ix_sales_sale_date'), 'sales', ['sale_date'], unique=False)
    op.create_table('transformation_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('vehicle_type', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('wage_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_code', sa.String(length=100), nullable=False),
    sa.Column('plantation_id', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('parent_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['plantation_id'], ['plantations.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['batch_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_batch_code'), 'batches', ['batch_code'], unique=True)
    op.create_table('consumable_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consumable_id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remaining_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('supplier', sa.String(length=200), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('remaining_quantity <= quantity', name='check_remaining_lte_quantity'),
    sa.CheckConstraint('remaining_quantity >= 0', name='check_remaining_positive'),
    sa.ForeignKeyConstraint(['consumable_id'], ['consumables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_consumable_purchase_fifo', 'consumable_purchases', ['consumable_id', 'purchase_date'], unique=False)
    op.create_index(op.f('ix_consumable_purchases_consumable_id'), 'consumable_purchases', ['consumable_id'], unique=False)
    op.create_index(op.f('ix_consumable_purchases_purchase_date'), 'consumable_purchases', ['purchase_date'], unique=False)
    op.create_table('personnel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('wage_type_id', sa.Integer(), nullable=False),
    sa.Column('current_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wage_type_id'], ['wage_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transformations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['transformation_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transformations_date'), 'transformations', ['date'], unique=False)
    op.create_table('consumable_consumptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transformation_id', sa.Integer(), nullable=False),
    sa.Column('consumable_id', sa.Integer(), nullable=False),
    sa.Column('consumption_date', sa.DateTime(), nullable=False),
    sa.Column('quantity_used', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consumable_id'], ['consumables.id'], ),
    sa.ForeignKeyConstraint(['transformation_id'], ['transformations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_consumption_transform_consumable', 'consumable_consumptions', ['transformation_id', 'consumable_id'], unique=False)
    op.create_index(op.f('ix_consumable_consumptions_consumable_id'), 'consumable_consumptions', ['consumable_id'], unique=False)
    op.create_index(op.f('ix_consumable_consumptions_consumption_date'), 'consumable_consumptions', ['consumption_date'], unique=False)
    op.create_index(op.f('ix_consumable_consumptions_transformation_id'), 'consumable_consumptions', ['transformation_id'], unique=False)
    op.create_table('retail_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remaining_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('remaining_quantity <= quantity', name='check_retail_remaining_lte_quantity'),
    sa.CheckConstraint('remaining_quantity >= 0', name='check_retail_remaining_positive'),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_retail_inventory_fifo', 'retail_inventory', ['created_date'], unique=False)
    op.create_index(op.f('ix_retail_inventory_batch_id'), 'retail_inventory', ['batch_id'], unique=True)
    op.create_index(op.f('ix_retail_inventory_created_date'), 'retail_inventory', ['created_date'], unique=False)
    op.create_table('transformation_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transformation_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('input_weight', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['transformation_id'], ['transformations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transformation_id', 'batch_id', name='uq_transformation_input_batch')
    )
    op.create_index(op.f('ix_transformation_inputs_batch_id'), 'transformation_inputs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_transformation_inputs_transformation_id'), 'transformation_inputs', ['transformation_id'], unique=False)
    op.create_table('transformation_outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transformation_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('output_weight', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['transformation_id'], ['transformations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transformation_id', 'batch_id', name='uq_transformation_output_batch')
    )
    op.create_index(op.f('ix_transformation_outputs_batch_id'), 'transformation_outputs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_transformation_outputs_transformation_id'), 'transformation_outputs', ['transformation_id'], unique=False)
    op.create_table('transformation_personnel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transformation_id', sa.Integer(), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('assignment_date', sa.DateTime(), nullable=False),
    sa.Column('wage_type_at_time', sa.Integer(), nullable=False),
    sa.Column('rate_at_time', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('days_worked', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('output_weight_considered', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('additional_payments', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('additional_payments_description', sa.String(length=100), nullable=True),
    sa.Column('wage_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ),
    sa.ForeignKeyConstraint(['transformation_id'], ['transformations.id'], ),
    sa.ForeignKeyConstraint(['wage_type_at_time'], ['wage_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transformation_id', 'personnel_id', name='uq_transformation_personnel')
    )
    op.create_index(op.f('ix_transformation_personnel_assignment_date'), 'transformation_personnel', ['assignment_date'], unique=False)
    op.create_index(op.f('ix_transformation_personnel_personnel_id'), 'transformation_personnel', ['personnel_id'], unique=False)
    op.create_index(op.f('ix_transformation_personnel_transformation_id'), 'transformation_personnel', ['transformation_id'], unique=False)
    op.create_table('transformation_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transformation_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('hours_used', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('fuel_consumed', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['transformation_id'], ['transformations.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transformation_id', 'vehicle_id', name='uq_transformation_vehicle')
    )
    op.create_index(op.f('ix_transformation_vehicles_transformation_id'), 'transformation_vehicles', ['transformation_id'], unique=False)
    op.create_index(op.f('ix_transformation_vehicles_vehicle_id'), 'transformation_vehicles', ['vehicle_id'], unique=False)
    op.create_table('consumption_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consumption_id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('quantity_allocated', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_allocated > 0', name='check_allocation_positive'),
    sa.ForeignKeyConstraint(['consumption_id'], ['consumable_consumptions.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['consumable_purchases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumption_allocations_consumption_id'), 'consumption_allocations', ['consumption_id'], unique=False)
    op.create_index(op.f('ix_consumption_allocations_purchase_id'), 'consumption_allocations', ['purchase_id'], unique=False)
    op.create_table('sale_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('quantity_allocated', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_allocated', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_allocated > 0', name='check_sale_allocation_positive'),
    sa.ForeignKeyConstraint(['inventory_id'], ['retail_inventory.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_allocations_inventory_id'), 'sale_allocations', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_sale_allocations_sale_id'), 'sale_allocations', ['sale_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_allocations_sale_id'), table_name='sale_allocations')
    op.drop_index(op.f('ix_sale_allocations_inventory_id'), table_name='sale_allocations')
    op.drop_table('sale_allocations')
    op.drop_index(op.f('ix_consumption_allocations_purchase_id'), table_name='consumption_allocations')
    op.drop_index(op.f('ix_consumption_allocations_consumption_id'), table_name='consumption_allocations')
    op.drop_table('consumption_allocations')
    op.drop_index(op.f('ix_transformation_vehicles_vehicle_id'), table_name='transformation_vehicles')
    op.drop_index(op.f('ix_transformation_vehicles_transformation_id'), table_name='transformation_vehicles')
    op.drop_table('transformation_vehicles')
    op.drop_index(op.f('ix_transformation_personnel_transformation_id'), table_name='transformation_personnel')
    op.drop_index(op.f('ix_transformation_personnel_personnel_id'), table_name='transformation_personnel')
    op.drop_index(op.f('ix_transformation_personnel_assignment_date'), table_name='transformation_personnel')
    op.drop_table('transformation_personnel')
    op.drop_index(op.f('ix_transformation_outputs_transformation_id'), table_name='transformation_outputs')
    op.drop_index(op.f('ix_transformation_outputs_batch_id'), table_name='transformation_outputs')
    op.drop_table('transformation_outputs')
    op.drop_index(op.f('ix_transformation_inputs_transformation_id'), table_name='transformation_inputs')
    op.drop_index(op.f('ix_transformation_inputs_batch_id'), table_name='transformation_inputs')
    op.drop_table('transformation_inputs')
    op.drop_index(op.f('ix_retail_inventory_created_date'), table_name='retail_inventory')
    op.drop_index(op.f('ix_retail_inventory_batch_id'), table_name='retail_inventory')
    op.drop_index('idx_retail_inventory_fifo', table_name='retail_inventory')
    op.drop_table('retail_inventory')
    op.drop_index(op.f('ix_consumable_consumptions_transformation_id'), table_name='consumable_consumptions')
    op.drop_index(op.f('ix_consumable_consumptions_consumption_date'), table_name='consumable_consumptions')
    op.drop_index(op.f('ix_consumable_consumptions_consumable_id'), table_name='consumable_consumptions')
    op.drop_index('idx_consumption_transform_consumable', table_name='consumable_consumptions')
    op.drop_table('consumable_consumptions')
    op.drop_index(op.f('ix_transformations_date'), table_name='transformations')
    op.drop_table('transformations')
    op.drop_table('personnel')
    op.drop_index(op.f('ix_consumable_purchases_purchase_date'), table_name='consumable_purchases')
    op.drop_index(op.f('ix_consumable_purchases_consumable_id'), table_name='consumable_purchases')
    op.drop_index('idx_consumable_purchase_fifo', table_name='consumable_purchases')
    op.drop_table('consumable_purchases')
    op.drop_index(op.f('ix_batches_batch_code'), table_name='batches')
    op.drop_table('batches')
    op.drop_table('wage_types')
    op.drop_table('vehicles')
    op.drop_table('transformation_types')
    op.drop_index(op.f('ix_sales_sale_date'), table_name='sales')
    op.drop_index('idx_sale_date', table_name='sales')
    op.drop_table('sales')
    op.drop_table('plantations')
    op.drop_index(op.f('ix_consumables_name'), table_name='consumables')
    op.drop_table('consumables')
    op.drop_table('batch_stages')
    # ### end Alembic commands ###
