"""core_logic_fixes

Revision ID: 8bc7955f0bdb
Revises: 2b61689ecbac
Create Date: 2026-03-15 21:38:23.995939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8bc7955f0bdb'
down_revision: Union[str, Sequence[str], None] = '2b61689ecbac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('batch_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consumable_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumable_categories_name'), 'consumable_categories', ['name'], unique=True)
    op.create_table('expense_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_categories_name'), 'expense_categories', ['name'], unique=True)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_city'), 'locations', ['city'], unique=True)
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.DateTime(), nullable=False),
    sa.Column('quantity_sold', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_of_goods_sold', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('customer_address', sa.String(length=500), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sale_date', 'sales', ['sale_date'], unique=False)
    op.create_index(op.f('ix_sales_sale_date'), 'sales', ['sale_date'], unique=False)
    op.create_table('transformation_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_root', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('wage_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('consumables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['consumable_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumables_name'), 'consumables', ['name'], unique=True)
    op.create_table('personnel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(length=500), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('wage_type_id', sa.Integer(), nullable=False),
    sa.Column('current_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wage_type_id'], ['wage_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plantations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('area_hectares', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('transformations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('from_date', sa.DateTime(), nullable=False),
    sa.Column('to_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['transformation_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transformations_from_date'), 'transformations', ['from_date'], unique=False)
    op.create_index(op.f('ix_transformations_to_date'), 'transformations', ['to_date'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_fetched_at'), 'weather', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_weather_id'), 'weather', ['id'], unique=False)
    op.create_index(op.f('ix_weather_location_id'), 'weather', ['location_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_requested_by_id'), 'approval_requests', ['requested_by_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_status'), 'approval_requests', ['status'], unique=False)
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_code', sa.String(length=100), nullable=False),
    sa.Column('plantation_id', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('initial_weight_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remaining_weight_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_depleted', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plantation_id'], ['plantations.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['batch_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_batch_code'), 'batches', ['batch_code'], unique=True)
    op.create_index(op.f('ix_batches_is_depleted'), 'batches', ['is_depleted'], unique=False)
    op.create_table('consumable_consumptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transformation_id', sa.Integer(), nullable=False),
    sa.Column('consumable_id', sa.Integer(), nullable=False),
    sa.Column('consumption_date', sa.DateTime(), nullable=False),
    sa.Column('quantity_used', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_vehicle_fuel', sa.Boolean(), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consumable_id'], ['consumables.id'], ),
    sa.ForeignKeyConstraint(['transformation_id'], ['transformations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_consumption_transform_consumable', 'consumable_consumptions', ['transformation_id', 'consumable_id'], unique=False)
    op.create_index(op.f('ix_consumable_consumptions_consumable_id'), 'consumable_consumptions', ['consumable_id'], unique=False)
    op.create_index(op.f('ix_consumable_consumptions_consumption_date'), 'consumable_consumptions', ['consumption_date'], unique=False)
    op.create_index(op.f('ix_consumable_consumptions_transformation_id'), 'consumable_consumptions', ['transformation_id'], unique=False)
    op.create_table('plantation_leases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plantation_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['plantation_id'], ['plantations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('vehicle_type', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fuel_consumable_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fuel_consumable_id'], ['consumables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('batch_parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_batch_id', sa.Integer(), nullable=False),
    sa.Column('parent_batch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_batch_id', 'parent_batch_id', name='uq_batch_parent')
    )
    op.create_index(op.f('ix_batch_parents_child_batch_id'), 'batch_parents', ['child_batch_id'], unique=False)
    op.create_index(op.f('ix_batch_parents_parent_batch_id'), 'batch_parents', ['parent_batch_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('plantation_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('transformation_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('receipt_image', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ),
    sa.ForeignKeyConstraint(['plantation_id'], ['plantations.id'], ),
    sa.ForeignKeyConstraint(['transformation_id'], ['transformations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_date'), 'expenses', ['date'], unique=False)
    op.create_table('retail_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remaining_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('remaining_quantity <= quantity', name='check_retail_remaining_lte_quantity'),
    sa.CheckConstraint('remaining_quantity >= 0', name='check_retail_remaining_positive'),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_retail_inventory_fifo', 'retail_inventory', ['created_date'], unique=False)
    op.create_index(op.f('ix_retail_inventory_batch_id'), 'retail_inventory', ['batch_id'], unique=True)
    op.create_index(op.f('ix_retail_inventory_created_date'), 'retail_inventory', ['created_date'], unique=False)
    op.create_table('transformation_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transformation_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('input_weight', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['transformation_id'], ['transformations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transformation_id', 'batch_id', name='uq_transformation_input_batch')
    )
    op.create_index(op.f('ix_transformation_inputs_batch_id'), 'transformation_inputs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_transformation_inputs_transformation_id'), 'transformation_inputs', ['transformation_id'], unique=False)
    op.create_table('transformation_outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transformation_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('output_weight', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['transformation_id'], ['transformations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transformation_id', 'batch_id', name='uq_transformation_output_batch')
    )
    op.create_index(op.f('ix_transformation_outputs_batch_id'), 'transformation_outputs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_transformation_outputs_transformation_id'), 'transformation_outputs', ['transformation_id'], unique=False)
    op.create_table('transformation_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transformation_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('hours_used', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('fuel_qty', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('fuel_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('consumable_consumption_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['consumable_consumption_id'], ['consumable_consumptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transformation_id'], ['transformations.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transformation_vehicles_transformation_id'), 'transformation_vehicles', ['transformation_id'], unique=False)
    op.create_index(op.f('ix_transformation_vehicles_vehicle_id'), 'transformation_vehicles', ['vehicle_id'], unique=False)
    op.create_table('consumable_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consumable_id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remaining_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('supplier', sa.String(length=200), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('remaining_quantity <= quantity', name='check_remaining_lte_quantity'),
    sa.CheckConstraint('remaining_quantity >= 0', name='check_remaining_positive'),
    sa.ForeignKeyConstraint(['consumable_id'], ['consumables.id'], ),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_consumable_purchase_fifo', 'consumable_purchases', ['consumable_id', 'purchase_date'], unique=False)
    op.create_index(op.f('ix_consumable_purchases_consumable_id'), 'consumable_purchases', ['consumable_id'], unique=False)
    op.create_index(op.f('ix_consumable_purchases_purchase_date'), 'consumable_purchases', ['purchase_date'], unique=False)
    op.create_table('sale_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('quantity_allocated', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_allocated', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_allocated > 0', name='check_sale_allocation_positive'),
    sa.ForeignKeyConstraint(['inventory_id'], ['retail_inventory.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_allocations_inventory_id'), 'sale_allocations', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_sale_allocations_sale_id'), 'sale_allocations', ['sale_id'], unique=False)
    op.create_table('transformation_personnel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transformation_id', sa.Integer(), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('assignment_date', sa.DateTime(), nullable=False),
    sa.Column('wage_type_at_time_id', sa.Integer(), nullable=False),
    sa.Column('rate_at_time', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('days_worked', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('output_weight_considered', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('additional_payments', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('additional_payments_description', sa.String(length=100), nullable=True),
    sa.Column('base_wage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_wages_payable', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ),
    sa.ForeignKeyConstraint(['transformation_id'], ['transformations.id'], ),
    sa.ForeignKeyConstraint(['wage_type_at_time_id'], ['wage_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transformation_id', 'personnel_id', name='uq_transformation_personnel')
    )
    op.create_index(op.f('ix_transformation_personnel_assignment_date'), 'transformation_personnel', ['assignment_date'], unique=False)
    op.create_index(op.f('ix_transformation_personnel_personnel_id'), 'transformation_personnel', ['personnel_id'], unique=False)
    op.create_index(op.f('ix_transformation_personnel_transformation_id'), 'transformation_personnel', ['transformation_id'], unique=False)
    op.create_table('consumption_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consumption_id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('quantity_allocated', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_allocated > 0', name='check_allocation_positive'),
    sa.ForeignKeyConstraint(['consumption_id'], ['consumable_consumptions.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['consumable_purchases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumption_allocations_consumption_id'), 'consumption_allocations', ['consumption_id'], unique=False)
    op.create_index(op.f('ix_consumption_allocations_purchase_id'), 'consumption_allocations', ['purchase_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consumption_allocations_purchase_id'), table_name='consumption_allocations')
    op.drop_index(op.f('ix_consumption_allocations_consumption_id'), table_name='consumption_allocations')
    op.drop_table('consumption_allocations')
    op.drop_index(op.f('ix_transformation_personnel_transformation_id'), table_name='transformation_personnel')
    op.drop_index(op.f('ix_transformation_personnel_personnel_id'), table_name='transformation_personnel')
    op.drop_index(op.f('ix_transformation_personnel_assignment_date'), table_name='transformation_personnel')
    op.drop_table('transformation_personnel')
    op.drop_index(op.f('ix_sale_allocations_sale_id'), table_name='sale_allocations')
    op.drop_index(op.f('ix_sale_allocations_inventory_id'), table_name='sale_allocations')
    op.drop_table('sale_allocations')
    op.drop_index(op.f('ix_consumable_purchases_purchase_date'), table_name='consumable_purchases')
    op.drop_index(op.f('ix_consumable_purchases_consumable_id'), table_name='consumable_purchases')
    op.drop_index('idx_consumable_purchase_fifo', table_name='consumable_purchases')
    op.drop_table('consumable_purchases')
    op.drop_index(op.f('ix_transformation_vehicles_vehicle_id'), table_name='transformation_vehicles')
    op.drop_index(op.f('ix_transformation_vehicles_transformation_id'), table_name='transformation_vehicles')
    op.drop_table('transformation_vehicles')
    op.drop_index(op.f('ix_transformation_outputs_transformation_id'), table_name='transformation_outputs')
    op.drop_index(op.f('ix_transformation_outputs_batch_id'), table_name='transformation_outputs')
    op.drop_table('transformation_outputs')
    op.drop_index(op.f('ix_transformation_inputs_transformation_id'), table_name='transformation_inputs')
    op.drop_index(op.f('ix_transformation_inputs_batch_id'), table_name='transformation_inputs')
    op.drop_table('transformation_inputs')
    op.drop_index(op.f('ix_retail_inventory_created_date'), table_name='retail_inventory')
    op.drop_index(op.f('ix_retail_inventory_batch_id'), table_name='retail_inventory')
    op.drop_index('idx_retail_inventory_fifo', table_name='retail_inventory')
    op.drop_table('retail_inventory')
    op.drop_index(op.f('ix_expenses_date'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_batch_parents_parent_batch_id'), table_name='batch_parents')
    op.drop_index(op.f('ix_batch_parents_child_batch_id'), table_name='batch_parents')
    op.drop_table('batch_parents')
    op.drop_table('vehicles')
    op.drop_table('user_roles')
    op.drop_table('plantation_leases')
    op.drop_index(op.f('ix_consumable_consumptions_transformation_id'), table_name='consumable_consumptions')
    op.drop_index(op.f('ix_consumable_consumptions_consumption_date'), table_name='consumable_consumptions')
    op.drop_index(op.f('ix_consumable_consumptions_consumable_id'), table_name='consumable_consumptions')
    op.drop_index('idx_consumption_transform_consumable', table_name='consumable_consumptions')
    op.drop_table('consumable_consumptions')
    op.drop_index(op.f('ix_batches_is_depleted'), table_name='batches')
    op.drop_index(op.f('ix_batches_batch_code'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_approval_requests_status'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_requested_by_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_weather_location_id'), table_name='weather')
    op.drop_index(op.f('ix_weather_id'), table_name='weather')
    op.drop_index(op.f('ix_weather_fetched_at'), table_name='weather')
    op.drop_table('weather')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_transformations_to_date'), table_name='transformations')
    op.drop_index(op.f('ix_transformations_from_date'), table_name='transformations')
    op.drop_table('transformations')
    op.drop_table('plantations')
    op.drop_table('personnel')
    op.drop_index(op.f('ix_consumables_name'), table_name='consumables')
    op.drop_table('consumables')
    op.drop_table('wage_types')
    op.drop_table('transformation_types')
    op.drop_index(op.f('ix_sales_sale_date'), table_name='sales')
    op.drop_index('idx_sale_date', table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_city'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_expense_categories_name'), table_name='expense_categories')
    op.drop_table('expense_categories')
    op.drop_index(op.f('ix_consumable_categories_name'), table_name='consumable_categories')
    op.drop_table('consumable_categories')
    op.drop_table('batch_stages')
    op.drop_table('app_config')
    # ### end Alembic commands ###
