"""fix_personnel_photo_type

Revision ID: 956695790b8c
Revises: fe615d798bc7
Create Date: 2026-03-09 11:25:43.921382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '956695790b8c'
down_revision: Union[str, Sequence[str], None] = 'fe615d798bc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personnel', 'photo',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personnel', 'photo',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
