"""Modified plantations history

Revision ID: b20c3bab0ab4
Revises: 1a337b5d8c38
Create Date: 2026-02-21 10:35:57.056698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b20c3bab0ab4'
down_revision: Union[str, Sequence[str], None] = '1a337b5d8c38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plantations', 'lease_start')
    op.drop_column('plantations', 'lease_end')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plantations', sa.Column('lease_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('plantations', sa.Column('lease_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
