"""sales feature models

Revision ID: c150263c93e2
Revises: 40c37e66c12a
Create Date: 2026-03-17 11:57:26.502644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c150263c93e2'
down_revision: Union[str, Sequence[str], None] = '40c37e66c12a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=True)
    # Drop the FK from sale_allocations referencing retail_inventory before dropping the table
    op.drop_constraint(op.f('sale_allocations_inventory_id_fkey'), 'sale_allocations', type_='foreignkey')
    op.drop_index(op.f('idx_retail_inventory_fifo'), table_name='retail_inventory')
    op.drop_index(op.f('ix_retail_inventory_batch_id'), table_name='retail_inventory')
    op.drop_index(op.f('ix_retail_inventory_created_date'), table_name='retail_inventory')
    op.drop_table('retail_inventory')
    # Add is_salable with a server_default so existing rows get FALSE
    op.add_column('batch_stages', sa.Column('is_salable', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('batches', sa.Column('cost_per_kg', sa.Numeric(precision=10, scale=2), nullable=True))
    # Add batch_id as nullable first (existing rows have no value), then set NOT NULL after populating
    op.add_column('sale_allocations', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_sale_allocations_inventory_id'), table_name='sale_allocations')
    op.create_index(op.f('ix_sale_allocations_batch_id'), 'sale_allocations', ['batch_id'], unique=False)
    op.create_foreign_key(None, 'sale_allocations', 'batches', ['batch_id'], ['id'])
    op.drop_column('sale_allocations', 'inventory_id')
    # Add NOT NULL sales columns as nullable first (existing rows have no value)
    op.add_column('sales', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('stage_id', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('status', sa.String(length=20), nullable=True, server_default=sa.text("'COMPLETED'")))
    op.add_column('sales', sa.Column('allocation_mode', sa.String(length=10), nullable=True, server_default=sa.text("'FIFO'")))
    op.add_column('sales', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('reviewed_by_id', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('sales', sa.Column('rejection_reason', sa.String(length=500), nullable=True))
    op.add_column('sales', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_sales_customer_id'), 'sales', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_stage_id'), 'sales', ['stage_id'], unique=False)
    op.create_index(op.f('ix_sales_status'), 'sales', ['status'], unique=False)
    op.create_foreign_key(None, 'sales', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'sales', 'batch_stages', ['stage_id'], ['id'])
    op.create_foreign_key(None, 'sales', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'sales', 'users', ['reviewed_by_id'], ['id'])
    op.drop_column('sales', 'customer_address')
    op.drop_column('sales', 'customer_phone')
    op.drop_column('sales', 'customer_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('customer_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('sales', sa.Column('customer_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('sales', sa.Column('customer_address', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_status'), table_name='sales')
    op.drop_index(op.f('ix_sales_stage_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_customer_id'), table_name='sales')
    op.drop_column('sales', 'updated_at')
    op.drop_column('sales', 'rejection_reason')
    op.drop_column('sales', 'reviewed_at')
    op.drop_column('sales', 'reviewed_by_id')
    op.drop_column('sales', 'created_by_id')
    op.drop_column('sales', 'allocation_mode')
    op.drop_column('sales', 'status')
    op.drop_column('sales', 'stage_id')
    op.drop_column('sales', 'customer_id')
    op.add_column('sale_allocations', sa.Column('inventory_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sale_allocations', type_='foreignkey')
    op.create_foreign_key(op.f('sale_allocations_inventory_id_fkey'), 'sale_allocations', 'retail_inventory', ['inventory_id'], ['id'])
    op.drop_index(op.f('ix_sale_allocations_batch_id'), table_name='sale_allocations')
    op.create_index(op.f('ix_sale_allocations_inventory_id'), 'sale_allocations', ['inventory_id'], unique=False)
    op.drop_column('sale_allocations', 'batch_id')
    op.drop_column('batches', 'cost_per_kg')
    op.drop_column('batch_stages', 'is_salable')
    op.create_table('retail_inventory',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('remaining_quantity', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('cost_per_kg', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('remaining_quantity <= quantity', name=op.f('check_retail_remaining_lte_quantity')),
    sa.CheckConstraint('remaining_quantity >= 0::numeric', name=op.f('check_retail_remaining_positive')),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('retail_inventory_batch_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('retail_inventory_pkey'))
    )
    op.create_index(op.f('ix_retail_inventory_created_date'), 'retail_inventory', ['created_date'], unique=False)
    op.create_index(op.f('ix_retail_inventory_batch_id'), 'retail_inventory', ['batch_id'], unique=True)
    op.create_index(op.f('idx_retail_inventory_fifo'), 'retail_inventory', ['created_date'], unique=False)
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
