"""Modified plantations history

Revision ID: db34b625531a
Revises: b20c3bab0ab4
Create Date: 2026-02-21 10:45:30.558974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db34b625531a'
down_revision: Union[str, Sequence[str], None] = 'b20c3bab0ab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plantation_leases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plantation_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['plantation_id'], ['plantations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('lease_histories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lease_histories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('plantation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('cost', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['plantation_id'], ['plantations.id'], name=op.f('lease_histories_plantation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lease_histories_pkey'))
    )
    op.drop_table('plantation_leases')
    # ### end Alembic commands ###
