"""add is_waste to batch_stages

Revision ID: 60b04bef0622
Revises: a0be8d365925
Create Date: 2026-03-24 12:08:54.451470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60b04bef0622'
down_revision: Union[str, Sequence[str], None] = 'a0be8d365925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch_stages', sa.Column('is_waste', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batch_stages', 'is_waste')
    # ### end Alembic commands ###
